### ISSUE TITLE
Strategy to merge configuration

### ISSUE THREAD

**Issue by reekoheek** [xinix-technology/bono#43]
Let say that the application will have 2 different mode of deployments, development and production. Each deployment will have different configuration on some fields. This issue is about how to manage that. The specification must follows:

- [x] MUST always read config.php 
- [x] MUST merge config.php with config-$mode.php values, ex: config-production.php
- [ ] MUST use deep merge mechanism
- [ ] MUST respect 'field!unset' => null, to unset 'field' value

**Comment by reekoheek** [comment]
implemented on master

**Comment by krisanalfa** [comment]
Cool. But still don't know how to implement it.

**Comment by reekoheek** [comment]
You can merge nested object configuration without defining new whole object. Eg

config.php
```
return [
  'foo' => [
     'bar' => 'some value'
  ]
];
```
config-production.php
```
return [
  'foo' => [
     'bar!unset' => null,
     'baz' => 'some value'
  ]
];
```

will merged into

```
return [
  'foo' => [
     'baz' => 'some value'
  ]
];
```

The config-production will unset bar and add new field baz. By default the array will be recursively merged
